### Get user profile
http://localhost:3000/user/profile
Authorization: Bearer {{$dotenv TOKEN}}


### Edit user profile
Post http://localhost:3000/user/profile
Authorization: Bearer {{$dotenv TOKEN}}
Content-Type: application/json

{
    "first_name": "pantea",
    "last_name": "rezaee",
    "skills": ["programmer", "java script", "HTML-CSS"]
}